name: Release Library

on:
  workflow_dispatch:

jobs:
  publish-library-to-maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
          cache: 'gradle'

      - name: Publish Library to Maven
        run: ./gradlew publishAllPublicationsToMavenCentral --no-configuration-cache
